version: "3.4"
services:
  #vpn: # disabled as VPN Routing now gets done somewhere else in my Network
    #image: dperson/openvpn-client:latest
    #cap_add:
    #  - net_admin # required to modify network interfaces
    #restart: unless-stopped
    #volumes:
    #  - /dev/net:/dev/net:z # tun device
    #  - ${ROOT}/config/vpn:/vpn # OpenVPN configuration
    #security_opt:
    #  - label:disable
    #ports:
    #  - 8112:8112 # port for deluge web UI to be reachable from local network
    #command: '-f "" -r 192.168.1.0/24' # enable firewall and route local network traffic

  deluge:
    image: linuxserver/deluge:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${NAS}/downloads:/downloads # downloads folder
      - ${NAS}/config/deluge:/config # config files
    ports:
      - target: 8112
        published: 8112
        protocol: tcp 
        mode: ${MODE}

      - target: 5846
        published: 5846
        protocol: tcp 
        mode: ${MODE}


  jackett:
   # container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${NAS}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${NAS}/config/jackett:/config # config files
    ports:
      - target: 9117
        published: 9117
        protocol: tcp 
        mode: ${MODE}


  sabnzbd:
    image: linuxserver/sabnzbd
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${NAS}/downloads:/downloads # download folder
      - ${NAS}/config/sabnzbd:/config # config files
    ports:
      - target: 8080
        published: 6799  # ####evtl switcged
        protocol: tcp 
        mode: ${MODE}

  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${NAS}/config/sonarr:/config # config files
      - ${NAS}/complete/tv:/tv # tv shows folder
      - ${NAS}/downloads:/downloads # download folder
    ports:
      - target: 8989
        published: 8989
        protocol: tcp 
        mode: ${MODE}

  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${NAS}/config/radarr:/config # config files
      - ${NAS}/complete/movies:/movies # movies folder
      - ${NAS}/downloads:/downloads # download folder
    ports:
      - target: 7878
        published: 7878
        protocol: tcp 
        mode: ${MODE}


  plex-server: # you could use Jellyfin instead ( FOSS )
    image: linuxserver/plex:${PLEXTAG}
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${NAS}/config/plex/db:/config # plex database
      - ${NAS}/plextranscode:/transcode # temp transcoded files
      - ${NAS}/complete:/data # media library
      - ${NAS}/complete/music:/music # music
    ports:
      - target: 32400
        published: 32400
        protocol: tcp 
        mode: ${MODE}

  bazarr:
    image: linuxserver/bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - ${NAS}/config/bazarr:/config # config files
      - ${NAS}/complete/movies:/movies # movies folder
      - ${NAS}/complete/tv:/tv # tv shows folder
    ports:
      - target: 6767
        published: 6767
        protocol: tcp 
        mode: ${MODE}

      
  prowlarr:
    image: linuxserver/prowlarr:nightly
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${NAS}/config/prowlarr:/config # config files
    ports:
      - target: 9696
        published: 9696
        protocol: tcp 
        mode: ${MODE}

      
  lidarr:
    image: linuxserver/lidarr:nightly
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${NAS}/config/lidarr:/config # config files
      - ${NAS}/complete/music:/music # music folder
      - ${NAS}/downloads:/downloads # download shows folder
    ports:
      - target: 8686
        published: 8686
        protocol: tcp 
        mode: ${MODE}

      
  readarr:
    image: linuxserver/readarr:nightly
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${NAS}/config/readarr:/config # config files
      - ${NAS}/complete/books:/books # music folder
      - ${NAS}/downloads:/downloads # download shows folder
    ports:
      - target: 8787
        published: 8787
        protocol: tcp 
        mode: ${MODE}
        

  


