version: '3.6'

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ${NAS}/nextcloud/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=YourPassword
      - MYSQL_PASSWORD=YourPassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: unless-stopped
    links:
      - db
    volumes:
      - ${NAS}/nextcloud/app:/var/www/html
    environment:
      - MYSQL_PASSWORD=YourPassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    ports:
      - target: 80
        published: 8080
        protocol: tcp 
        mode: ${MODE}
