version: "3.6"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/

services:
  pihole:
    image: pihole/pihole:latest
    environment:
      - TZ=${TZ} # timezone, defined in .env
      - WEBPASSWORD=YourPassword     #set a secure password here or it will be random
    volumes:
      - ${NAS}/pihole/config:/etc/pihole/
      - ${NAS}/pihole/dnsmasq:/etc/dnsmasq.d/
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    ports:
      - target: 53  
        published: 53  
        protocol: tcp 
        mode: ${MODE}
      - target: 53  
        published: 53  
        protocol: udp
        mode: ${MODE}
      - target: 67  
        published: 67  
        protocol: udp
        mode: ${MODE}
      - target: 8081   # I use 8081 on my host cause i want nextcloud on 8080
        published: 80  
        protocol: tcp 
        mode: ${MODE}
