version: "3.6"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/

services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8081:80/tcp"
    environment:
      - TZ=${TZ} # timezone, defined in .env
      - WEBPASSWORD=YourPassword     #set a secure password here or it will be random
    volumes:
      - ${NAS}/pihole/config:/etc/pihole/
      - ${NAS}/pihole/dnsmasq:/etc/dnsmasq.d/
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
