version: "2.1"
services:
  syncthing:
    image: linuxserver/syncthing:arm64v8-latest   #latest isn't device agnostic
    container_name: syncthing
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOTHDD}/downloads:/downloads # downloads folder
      - ${ROOT}/config/syncthing:/config # config files
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
