version: "3"
services: 
  traefik:
    image: traefik:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Webinterface
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock